### ISSUE TITLE
[BUG] MSYS missing DLLs

### ISSUE THREAD

**Issue by vintagepc** [vintagepc/MINI404#147]
Per #145 the MSYS zip is missing some DLLs. Once we know what they are, add them.

**Comment by BlueFyre** [comment]
Here are the ones I needed to copy over before Windows stopped throwing errors:
- libaom.dll
- libavif-16.dll
- libdav1d-7.dll
- libjxl_cms.dll
- libSvtAv1Enc.dll
- libwebpdemux-2.dll
- libyuv.dll
- rav1e.dll
